ROLLBACK;
BEGIN;

CREATE TABLE "time" (
                        "id_time"  INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                        "nome"     VARCHAR(100) NOT NULL,
                        "estado"   VARCHAR(50),
                        "cidade"   VARCHAR(50),
                        "estadio"  VARCHAR(100)
);

CREATE TABLE "jogador" (
                           "id_jogador"    INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                           "nome"          VARCHAR(100) NOT NULL,
                           "posicao"       VARCHAR(30)
                               CHECK ("posicao" IN ('Goleiro', 'Zagueiro', 'Lateral', 'Volante', 'Meia', 'Atacante')),
                           "numero_camisa" INT CHECK ("numero_camisa" > 0),
                           "idade"         INT CHECK ("idade" BETWEEN 15 AND 50),
                           "id_time"       INT
);

CREATE TABLE "partida" (
                           "id_partida"        INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                           "id_time_casa"      INT NOT NULL,
                           "id_time_visitante" INT NOT NULL,
                           "gols_casa"         INT DEFAULT 0 CHECK ("gols_casa" >= 0),
                           "gols_visitante"    INT DEFAULT 0 CHECK ("gols_visitante" >= 0),
                           "data_partida"      DATE NOT NULL,
                           "local_partida"     VARCHAR(100)
);

COMMIT;
